<?php
/**
 * OGP Fetcher
 *
 * OGPデータを取得するクラス
 *
 * @package Slemb
 */

namespace Slemb;

// 万全の防御策
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Class OGP_Fetcher
 */
class OGP_Fetcher {

    /**
     * インスタンス
     *
     * @var OGP_Fetcher|null
     */
    private static $instance = null;

    /**
     * コンストラクタ
     */
    private function __construct() {
    }

    /**
     * インスタンスを取得
     *
     * @return OGP_Fetcher
     */
    public static function get_instance() {
        if ( null === self::$instance ) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * URLからOGPデータを取得
     *
     * @param string $url URL
     * @return array|\WP_ERROR OGPデータまたはエラー
     */
    public function fetch( $url ) {
        // URLのバリデーション
        if ( empty( $url ) ) {
            return new \WP_Error( 'empty_url', __( 'URLが空です。', 'simple-link-embed' ) );
        }

        if ( ! filter_var( $url, FILTER_VALIDATE_URL ) ) {
            return new \WP_Error( 'invalid_url', __( '無効なURLです。', 'simple-link-embed' ) );
        }

        // SSRF対策：URLスキームとホストの検証
        $parsed = wp_parse_url( $url );
        
        // HTTP/HTTPSのみ許可
        if ( ! isset( $parsed['scheme'] ) || ! in_array( $parsed['scheme'], array( 'http', 'https' ), true ) ) {
            return new \WP_Error( 'invalid_scheme', __( '許可されていないURLスキームです。', 'simple-link-embed' ) );
        }
        
        // ホストの検証
        $host = isset( $parsed['host'] ) ? strtolower( rtrim( $parsed['host'], '.' ) ) : '';
        $host = trim( $host, '[]' );
        if ( empty( $host ) ) {
            return new \WP_Error( 'invalid_host', __( '無効なホストです。', 'simple-link-embed' ) );
        }

        // ローカルホストと内部アドレスをブロック
        $blocked_hosts = array( 'localhost', '127.0.0.1', '0.0.0.0', '::1', '169.254.169.254' );
        if ( in_array( $host, $blocked_hosts, true ) ) {
            return new \WP_Error( 'blocked_host', __( 'アクセスが制限されているホストです。', 'simple-link-embed' ) );
        }

        // ローカル用途で使われるTLDをブロック
        $blocked_host_suffixes = array( '.localhost', '.local', '.internal' );
        foreach ( $blocked_host_suffixes as $suffix ) {
            if ( $suffix === substr( $host, -strlen( $suffix ) ) ) {
                return new \WP_Error( 'blocked_host', __( 'アクセスが制限されているホストです。', 'simple-link-embed' ) );
            }
        }

        // IPアドレスの場合、プライベート範囲をブロック
        $ip = filter_var( $host, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 | FILTER_FLAG_IPV6 );
        if ( $ip !== false ) {
            if ( ! $this->is_public_ip_address( $ip ) ) {
                return new \WP_Error( 'private_ip_blocked', __( 'プライベートIPアドレスへのアクセスは許可されていません。', 'simple-link-embed' ) );
            }
        }

        // ドメイン名の場合、名前解決後のIPが内部向けでないことを確認（DNS Rebinding対策）
        if ( false === $ip ) {
            $resolved_ips = $this->resolve_host_ips( $host );
            if ( empty( $resolved_ips ) ) {
                return new \WP_Error( 'invalid_host', __( '無効なホストです。', 'simple-link-embed' ) );
            }

            foreach ( $resolved_ips as $resolved_ip ) {
                if ( ! $this->is_public_ip_address( $resolved_ip ) ) {
                    return new \WP_Error( 'private_ip_blocked', __( 'プライベートIPアドレスへのアクセスは許可されていません。', 'simple-link-embed' ) );
                }
            }
        }

        // WordPressの安全なURL検証（DNS解決を含む）
        $validated_url = wp_http_validate_url( $url );
        if ( false === $validated_url ) {
            return new \WP_Error( 'invalid_url', __( '無効なURLです。', 'simple-link-embed' ) );
        }

        $url = $this->normalize_youtube_url( $validated_url );

        // キャッシュのチェック
        $cache_manager = Cache_Manager::get_instance();
        $cached_data   = $cache_manager->get( $url );

        if ( false !== $cached_data ) {
            if ( ! $this->is_legacy_truncated_cache( $cached_data ) && ! $this->is_incomplete_youtube_cache( $url, $cached_data ) ) {
                return $cached_data;
            }

            // Remove old cached descriptions generated by previous 200-char truncation logic.
            $cache_manager->delete( $url );
        }

        // YouTubeの特別処理
        $youtube_data = $this->fetch_youtube_data( $url );
        if ( false !== $youtube_data ) {
            $cache_manager->set( $url, $youtube_data );
            return $youtube_data;
        }

        // X（Twitter）の特別処理
        $twitter_data = $this->fetch_twitter_data( $url );
        if ( $twitter_data !== false ) {
            $cache_manager->set( $url, $twitter_data );
            return $twitter_data;
        }

        // HTMLの取得
        $response = wp_safe_remote_get( $url, array(
            'timeout'             => 15,
            'sslverify'           => true,
            'user-agent'          => 'Mozilla/5.0 (compatible; SimpleLinkEmbed/1.0; +https://monopedia.jp)',
            'limit_response_size' => 500 * KB_IN_BYTES, // 500KB
            'reject_unsafe_urls'  => true,
        ) );

        if ( is_wp_error( $response ) ) {
            return new \WP_Error( 'http_error', $response->get_error_message() );
        }

        $status_code = wp_remote_retrieve_response_code( $response );
        if ( $status_code !== 200 ) {
            /* translators: %d: HTTP status code. */
            return new \WP_Error( 'http_error', sprintf( __( 'HTTPエラー: %d', 'simple-link-embed' ), $status_code ) );
        }

        $html = wp_remote_retrieve_body( $response );

        // HTMLの解析
        $ogp_data = $this->parse_html( $html, $url );

        if ( is_wp_error( $ogp_data ) ) {
            return $ogp_data;
        }

        // キャッシュに保存
        $cache_manager->set( $url, $ogp_data );

        /**
         * OGPデータフィルター
         *
         * @param array  $ogp_data 取得したOGPデータ
         * @param string $url      元のURL
         */
        return apply_filters( 'slemb_ogp_data', $ogp_data, $url );
    }

    /**
     * ホストをIPに解決
     *
     * @param string $host ホスト名
     * @return array<string> 解決されたIPアドレス一覧
     */
    private function resolve_host_ips( $host ) {
        $resolved_ips = array();

        if ( function_exists( 'dns_get_record' ) && defined( 'DNS_A' ) && defined( 'DNS_AAAA' ) ) {
            $dns_records = dns_get_record( $host, DNS_A | DNS_AAAA );
            if ( is_array( $dns_records ) ) {
                foreach ( $dns_records as $record ) {
                    if ( isset( $record['ip'] ) && is_string( $record['ip'] ) ) {
                        $resolved_ips[] = $record['ip'];
                    }
                    if ( isset( $record['ipv6'] ) && is_string( $record['ipv6'] ) ) {
                        $resolved_ips[] = $record['ipv6'];
                    }
                }
            }
        }

        // dns_get_record が使えない環境向けのフォールバック（IPv4のみ）
        if ( empty( $resolved_ips ) ) {
            $ipv4_records = gethostbynamel( $host );
            if ( is_array( $ipv4_records ) ) {
                $resolved_ips = array_merge( $resolved_ips, $ipv4_records );
            }
        }

        $resolved_ips = array_filter(
            array_unique( $resolved_ips ),
            static function ( $resolved_ip ) {
                return is_string( $resolved_ip ) && false !== filter_var( $resolved_ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 | FILTER_FLAG_IPV6 );
            }
        );

        return array_values( $resolved_ips );
    }

    /**
     * 公開IPかどうか
     *
     * @param string $ip IPアドレス
     * @return bool
     */
    private function is_public_ip_address( $ip ) {
        return false !== filter_var( $ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE );
    }

    /**
     * HTMLを解析してOGPデータを抽出
     *
     * @param string $html HTML
     * @param string $url  元のURL
     * @return array|\WP_ERROR OGPデータまたはエラー
     */
    private function parse_html( $html, $url ) {
        // DOMDocumentの準備（現在のlibxml設定を保存）
        $libxml_internal_errors = libxml_use_internal_errors( true );
        $dom = new \DOMDocument();

        // HTMLの読み込み（UTF-8エンコーディングを明示・PHP 8.2互換）
        $html = '<?xml encoding="UTF-8">' . $html;

        // エラー抑制を使用せず、libxmlで内部エラー処理
        $loaded = $dom->loadHTML( $html );
        libxml_clear_errors();

        if ( ! $loaded ) {
            libxml_use_internal_errors( $libxml_internal_errors ); // 設定を元に戻す
            return new \WP_Error( 'parse_error', __( 'HTMLの解析に失敗しました。', 'simple-link-embed' ) );
        }

        // XPathの準備
        $xpath = new \DOMXPath( $dom );

        // OGPデータの抽出
        $ogp_data = array(
            'title'       => $this->get_meta_content( $xpath, 'og:title' ),
            'description' => $this->get_meta_content( $xpath, 'og:description' ),
            'image'       => $this->get_meta_content( $xpath, 'og:image' ),
            'url'         => $this->get_meta_content( $xpath, 'og:url' ),
            'site_name'   => $this->get_meta_content( $xpath, 'og:site_name' ),
        );

        // フォールバックデータの取得
        if ( empty( $ogp_data['title'] ) ) {
            $ogp_data['title'] = $this->get_title( $xpath );
        }
        if ( empty( $ogp_data['description'] ) ) {
            $ogp_data['description'] = $this->get_meta_content( $xpath, 'description' );
        }
        if ( empty( $ogp_data['url'] ) ) {
            $ogp_data['url'] = $url;
        }

        // URLを絶対URLに変換
        if ( ! empty( $ogp_data['image'] ) ) {
            $ogp_data['image'] = $this->make_absolute_url( $ogp_data['image'], $url );
        }

        // ドメインの抽出
        $parsed_url = wp_parse_url( $url );
        $ogp_data['domain'] = isset( $parsed_url['host'] ) ? $parsed_url['host'] : '';

        // ファビコンのURL（Googleのサービスを使用）
        if ( ! empty( $ogp_data['domain'] ) ) {
            $ogp_data['favicon'] = 'https://www.google.com/s2/favicons?domain=' . urlencode( $ogp_data['domain'] ) . '&sz=32';
        }

        libxml_use_internal_errors( $libxml_internal_errors ); // 設定を元に戻す
        return $ogp_data;
    }

    /**
     * 旧バージョンで保存された省略キャッシュかどうかを判定
     *
     * @param mixed $cached_data キャッシュデータ
     * @return bool
     */
    private function is_legacy_truncated_cache( $cached_data ) {
        if ( ! is_array( $cached_data ) || empty( $cached_data['description'] ) || ! is_string( $cached_data['description'] ) ) {
            return false;
        }

        $description = trim( $cached_data['description'] );
        if ( '' === $description || '...' !== substr( $description, -3 ) ) {
            return false;
        }

        $length = function_exists( 'mb_strlen' ) ? mb_strlen( $description, 'UTF-8' ) : strlen( $description );
        return 203 === $length;
    }

    /**
     * YouTubeの不完全キャッシュかどうかを判定
     *
     * 過去実装でYouTubeのOGP取得に失敗したデータが保存されている場合、
     * 新しい取得ロジックを有効にするためキャッシュを破棄して再取得する。
     *
     * @param string $url         URL
     * @param mixed  $cached_data キャッシュデータ
     * @return bool
     */
    private function is_incomplete_youtube_cache( $url, $cached_data ) {
        if ( ! is_array( $cached_data ) ) {
            return false;
        }

        $parsed = wp_parse_url( $url );
        $host = isset( $parsed['host'] ) ? strtolower( $parsed['host'] ) : '';
        if ( ! $this->is_youtube_host( $host ) ) {
            return false;
        }

        $title = isset( $cached_data['title'] ) ? trim( (string) $cached_data['title'] ) : '';
        $image = isset( $cached_data['image'] ) ? trim( (string) $cached_data['image'] ) : '';
        $cached_url = isset( $cached_data['url'] ) ? trim( (string) $cached_data['url'] ) : '';
        $description = isset( $cached_data['description'] ) ? trim( (string) $cached_data['description'] ) : '';
        $video_id = $this->extract_youtube_video_id( $url );

        if ( '' === $title ) {
            return true;
        }

        // 動画URLはサムネイル必須、チャンネルURLは画像なしでも許容する。
        if ( '' !== $video_id && '' === $image ) {
            return true;
        }

        // 失敗時にURLそのものがタイトルになっているキャッシュは再取得対象。
        if ( $title === $url || ( '' !== $cached_url && $title === $cached_url ) ) {
            return true;
        }

        // チャンネルURLの汎用フォールバックは再取得して実データ取得を優先する。
        if ( $this->is_youtube_channel_url( $url ) && '' === $image ) {
            if ( __( 'YouTubeチャンネルページです。', 'simple-link-embed' ) === $description ) {
                return true;
            }
        }

        return false;
    }

    /**
     * メタタグのcontentを取得
     *
     * @param \DOMXPath $xpath      XPathオブジェクト
     * @param string    $property   プロパティ名またはname属性
     * @return string 内容
     */
    private function get_meta_content( $xpath, $property ) {
        // property属性で検索（OGP用）
        $query = sprintf( '//meta[@property="%s"]', $property );
        $nodes = $xpath->query( $query );

        if ( $nodes->length > 0 ) {
            return $nodes->item( 0 )->getAttribute( 'content' );
        }

        // name属性で検索（通常のmetaタグ用）
        $query = sprintf( '//meta[@name="%s"]', $property );
        $nodes = $xpath->query( $query );

        if ( $nodes->length > 0 ) {
            return $nodes->item( 0 )->getAttribute( 'content' );
        }

        return '';
    }

    /**
     * ページタイトルを取得
     *
     * @param \DOMXPath $xpath XPathオブジェクト
     * @return string タイトル
     */
    private function get_title( $xpath ) {
        // titleタグ
        $nodes = $xpath->query( '//title' );
        if ( $nodes->length > 0 ) {
            return trim( $nodes->item( 0 )->textContent );
        }

        // h1タグ（フォールバック）
        $nodes = $xpath->query( '//h1' );
        if ( $nodes->length > 0 ) {
            return trim( $nodes->item( 0 )->textContent );
        }

        return '';
    }

    /**
     * 相対URLを絶対URLに変換
     *
     * @param string $url    変換するURL
     * @param string $base   ベースURL
     * @return string 絶対URL
     */
    private function make_absolute_url( $url, $base ) {
        // 既に絶対URLの場合
        if ( preg_match( '#^https?://#i', $url ) ) {
            return $url;
        }

        // プロトコル相対URL
        if ( strpos( $url, '//' ) === 0 ) {
            $parsed = wp_parse_url( $base );
            $scheme = isset( $parsed['scheme'] ) ? $parsed['scheme'] : 'https';
            return $scheme . ':' . $url;
        }

        // 相対パス
        $parsed_base = wp_parse_url( $base );
        $scheme = isset( $parsed_base['scheme'] ) ? $parsed_base['scheme'] : 'https';
        $host = isset( $parsed_base['host'] ) ? $parsed_base['host'] : '';

        if ( strpos( $url, '/' ) === 0 ) {
            return $scheme . '://' . $host . $url;
        }

        // カレントディレクトリからの相対パス
        $path = isset( $parsed_base['path'] ) ? dirname( $parsed_base['path'] ) : '';
        return $scheme . '://' . $host . $path . '/' . $url;
    }

    /**
     * YouTubeの特別処理
     *
     * YouTubeは通常のスクレイピングでOGPが取得できないケースがあるため、
     * oEmbed APIからメタ情報を取得し、失敗時は動画IDからサムネイルを補完する。
     *
     * @param string $url URL
     * @return array|false OGPデータまたはfalse（YouTubeでない場合）
     */
    private function fetch_youtube_data( $url ) {
        $parsed = wp_parse_url( $url );
        $host = isset( $parsed['host'] ) ? strtolower( $parsed['host'] ) : '';

        if ( ! $this->is_youtube_host( $host ) ) {
            return false;
        }

        $video_id = $this->extract_youtube_video_id( $url );
        $oembed_url = 'https://www.youtube.com/oembed?format=json&url=' . rawurlencode( $url );

        $response = wp_safe_remote_get(
            $oembed_url,
            array(
                'timeout'             => 15,
                'sslverify'           => true,
                'user-agent'          => 'Mozilla/5.0 (compatible; SimpleLinkEmbed/1.0; +https://monopedia.jp)',
                'limit_response_size' => 64 * KB_IN_BYTES,
                'reject_unsafe_urls'  => true,
            )
        );

        if ( ! is_wp_error( $response ) && 200 === wp_remote_retrieve_response_code( $response ) ) {
            $body = wp_remote_retrieve_body( $response );
            $oembed = json_decode( $body, true );

            if ( is_array( $oembed ) && ! empty( $oembed['title'] ) ) {
                $title = sanitize_text_field( (string) $oembed['title'] );
                $author_name = isset( $oembed['author_name'] ) ? sanitize_text_field( (string) $oembed['author_name'] ) : '';
                $thumbnail = isset( $oembed['thumbnail_url'] ) ? esc_url_raw( (string) $oembed['thumbnail_url'] ) : '';

                if ( empty( $thumbnail ) && ! empty( $video_id ) ) {
                    $thumbnail = 'https://i.ytimg.com/vi/' . rawurlencode( $video_id ) . '/hqdefault.jpg';
                }

                $description = '';
                if ( '' !== $author_name ) {
                    /* translators: %s: YouTube channel or author name. */
                    $description = sprintf( __( '%s のYouTube動画です。', 'simple-link-embed' ), $author_name );
                }

                return array(
                    'title'       => $title,
                    'description' => $description,
                    'image'       => $thumbnail,
                    'url'         => $url,
                    'site_name'   => 'YouTube',
                    'domain'      => 'youtube.com',
                    'favicon'     => 'https://www.google.com/s2/favicons?domain=youtube.com&sz=32',
                );
            }
        }

        // oEmbedが使えないURL（@handle など）は、ページHTMLからOGPを直接抽出する。
        $scraped_data = $this->fetch_youtube_page_data( $url );
        if ( false !== $scraped_data ) {
            return $scraped_data;
        }

        // oEmbedが失敗しても動画IDが抽出できれば最低限のカード情報を返す。
        if ( '' !== $video_id ) {
            return array(
                'title'       => __( 'YouTube動画', 'simple-link-embed' ),
                'description' => __( 'YouTubeで再生できる動画です。', 'simple-link-embed' ),
                'image'       => 'https://i.ytimg.com/vi/' . rawurlencode( $video_id ) . '/hqdefault.jpg',
                'url'         => $url,
                'site_name'   => 'YouTube',
                'domain'      => 'youtube.com',
                'favicon'     => 'https://www.google.com/s2/favicons?domain=youtube.com&sz=32',
            );
        }

        // チャンネルURLでメタ情報が取れない場合の最終フォールバック。
        $channel_label = $this->extract_youtube_channel_label( $url );
        if ( '' !== $channel_label ) {
            /* translators: %s: YouTube handle or channel identifier. */
            $title = sprintf( __( '%s - YouTube', 'simple-link-embed' ), $channel_label );
            return array(
                'title'       => $title,
                'description' => __( 'YouTubeチャンネルページです。', 'simple-link-embed' ),
                'image'       => '',
                'url'         => $url,
                'site_name'   => 'YouTube',
                'domain'      => 'youtube.com',
                'favicon'     => 'https://www.google.com/s2/favicons?domain=youtube.com&sz=32',
            );
        }

        return false;
    }

    /**
     * YouTubeホストかどうかを判定
     *
     * @param string $host ホスト名
     * @return bool
     */
    private function is_youtube_host( $host ) {
        if ( ! is_string( $host ) || '' === $host ) {
            return false;
        }

        $normalized_host = strtolower( $host );
        return (
            'youtu.be' === $normalized_host
            || 'www.youtu.be' === $normalized_host
            || 1 === preg_match( '/(^|\.)youtube\.com$/', $normalized_host )
        );
    }

    /**
     * YouTube共有URLを正規化
     *
     * 共有リンクで付与される "si" パラメータを除去し、キャッシュ分散を防ぐ。
     *
     * @param string $url URL
     * @return string 正規化済みURL
     */
    private function normalize_youtube_url( $url ) {
        $parsed = wp_parse_url( $url );
        if ( ! is_array( $parsed ) || empty( $parsed['host'] ) ) {
            return $url;
        }

        $host = strtolower( (string) $parsed['host'] );
        if ( ! $this->is_youtube_host( $host ) ) {
            return $url;
        }

        if ( empty( $parsed['query'] ) ) {
            return $url;
        }

        parse_str( (string) $parsed['query'], $query_args );
        if ( ! is_array( $query_args ) ) {
            return $url;
        }

        unset( $query_args['si'] );
        $normalized_query = http_build_query( $query_args, '', '&', PHP_QUERY_RFC3986 );

        $scheme = isset( $parsed['scheme'] ) ? (string) $parsed['scheme'] : 'https';
        $auth = '';
        if ( isset( $parsed['user'] ) ) {
            $auth .= (string) $parsed['user'];
            if ( isset( $parsed['pass'] ) ) {
                $auth .= ':' . (string) $parsed['pass'];
            }
            $auth .= '@';
        }

        $port = isset( $parsed['port'] ) ? ':' . (int) $parsed['port'] : '';
        $path = isset( $parsed['path'] ) ? (string) $parsed['path'] : '';
        $fragment = isset( $parsed['fragment'] ) ? '#' . (string) $parsed['fragment'] : '';

        return $scheme . '://' . $auth . $host . $port . $path . ( '' !== $normalized_query ? '?' . $normalized_query : '' ) . $fragment;
    }

    /**
     * YouTubeページHTMLからOGPを抽出
     *
     * @param string $url URL
     * @return array|false OGPデータまたはfalse
     */
    private function fetch_youtube_page_data( $url ) {
        $response = wp_safe_remote_get(
            $url,
            array(
                'timeout'             => 15,
                'sslverify'           => true,
                'user-agent'          => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36',
                'headers'             => array(
                    'Accept-Language' => 'ja,en-US;q=0.9,en;q=0.8',
                ),
                'limit_response_size' => 2 * MB_IN_BYTES,
                'reject_unsafe_urls'  => true,
            )
        );

        if ( is_wp_error( $response ) || 200 !== wp_remote_retrieve_response_code( $response ) ) {
            return false;
        }

        $html = wp_remote_retrieve_body( $response );
        if ( '' === trim( (string) $html ) ) {
            return false;
        }

        $ogp_data = $this->parse_html( $html, $url );
        if ( is_wp_error( $ogp_data ) || ! is_array( $ogp_data ) ) {
            $ogp_data = array();
        }

        $ogp_data = wp_parse_args(
            $ogp_data,
            array(
                'title'       => '',
                'description' => '',
                'image'       => '',
                'url'         => $url,
                'site_name'   => 'YouTube',
            )
        );

        if ( $this->is_youtube_channel_url( $url ) ) {
            $channel_metadata = $this->extract_youtube_channel_metadata_from_html( $html, $url );

            if ( '' !== $channel_metadata['title'] ) {
                $ogp_data['title'] = $channel_metadata['title'];
            }

            if ( '' !== $channel_metadata['description'] ) {
                $ogp_data['description'] = $channel_metadata['description'];
            }

            if ( '' !== $channel_metadata['image'] && '' === trim( (string) $ogp_data['image'] ) ) {
                $ogp_data['image'] = $channel_metadata['image'];
            }
        }

        $title = isset( $ogp_data['title'] ) ? trim( (string) $ogp_data['title'] ) : '';
        $description = isset( $ogp_data['description'] ) ? trim( (string) $ogp_data['description'] ) : '';
        $image = isset( $ogp_data['image'] ) ? trim( (string) $ogp_data['image'] ) : '';

        if ( '' === $title && '' === $description && '' === $image ) {
            return false;
        }

        if ( empty( $ogp_data['url'] ) ) {
            $ogp_data['url'] = $url;
        }

        if ( empty( $ogp_data['site_name'] ) ) {
            $ogp_data['site_name'] = 'YouTube';
        }

        $ogp_data['domain'] = 'youtube.com';
        $ogp_data['favicon'] = 'https://www.google.com/s2/favicons?domain=youtube.com&sz=32';

        return $ogp_data;
    }

    /**
     * YouTubeのチャンネルURLかどうかを判定
     *
     * @param string $url URL
     * @return bool
     */
    private function is_youtube_channel_url( $url ) {
        $parsed = wp_parse_url( $url );
        if ( ! is_array( $parsed ) || empty( $parsed['path'] ) ) {
            return false;
        }

        $path = trim( (string) $parsed['path'], '/' );
        if ( '' === $path ) {
            return false;
        }

        $segments = array_values( array_filter( explode( '/', $path ), 'strlen' ) );
        if ( empty( $segments ) ) {
            return false;
        }

        $first_segment = (string) $segments[0];
        if ( 0 === strpos( $first_segment, '@' ) && strlen( $first_segment ) > 1 ) {
            return true;
        }

        return isset( $segments[1] ) && in_array( $first_segment, array( 'channel', 'c', 'user' ), true );
    }

    /**
     * YouTubeチャンネルページHTMLからチャンネルメタ情報を抽出
     *
     * @param string $html HTML
     * @param string $url  URL
     * @return array{title:string,description:string,image:string}
     */
    private function extract_youtube_channel_metadata_from_html( $html, $url ) {
        $metadata = array(
            'title'       => '',
            'description' => '',
            'image'       => '',
        );

        $libxml_internal_errors = libxml_use_internal_errors( true );
        $dom = new \DOMDocument();
        $loaded = $dom->loadHTML( '<?xml encoding="UTF-8">' . $html );
        libxml_clear_errors();

        if ( $loaded ) {
            $xpath = new \DOMXPath( $dom );

            $metadata['title'] = $this->extract_first_xpath_attribute(
                $xpath,
                array(
                    '//meta[@itemprop="name"]',
                    '//meta[@property="og:title"]',
                    '//meta[@name="twitter:title"]',
                    '//meta[@name="title"]',
                )
            );

            $metadata['description'] = $this->extract_first_xpath_attribute(
                $xpath,
                array(
                    '//meta[@itemprop="description"]',
                    '//meta[@property="og:description"]',
                    '//meta[@name="twitter:description"]',
                    '//meta[@name="description"]',
                )
            );

            $metadata['image'] = $this->extract_first_xpath_attribute(
                $xpath,
                array(
                    '//meta[@itemprop="thumbnailUrl"]',
                    '//meta[@property="og:image"]',
                    '//meta[@name="twitter:image"]',
                )
            );

            if ( '' === $metadata['image'] ) {
                $metadata['image'] = $this->extract_first_xpath_attribute(
                    $xpath,
                    array( '//link[@rel="image_src"]' ),
                    'href'
                );
            }
        }

        libxml_use_internal_errors( $libxml_internal_errors );

        $json_ld_metadata = $this->extract_youtube_channel_metadata_from_json_ld( $html, $url );
        $initial_data_metadata = $this->extract_youtube_channel_metadata_from_initial_data( $html );

        foreach ( array( $json_ld_metadata, $initial_data_metadata ) as $candidate ) {
            if ( '' === $metadata['title'] && '' !== $candidate['title'] ) {
                $metadata['title'] = $candidate['title'];
            }
            if ( '' === $metadata['description'] && '' !== $candidate['description'] ) {
                $metadata['description'] = $candidate['description'];
            }
            if ( '' === $metadata['image'] && '' !== $candidate['image'] ) {
                $metadata['image'] = $candidate['image'];
            }
        }

        $metadata['title'] = sanitize_text_field( $metadata['title'] );
        $metadata['description'] = sanitize_text_field( $metadata['description'] );
        $metadata['image'] = esc_url_raw( $metadata['image'] );

        return $metadata;
    }

    /**
     * YouTubeページのJSON-LDからチャンネルメタ情報を抽出
     *
     * @param string $html HTML
     * @param string $url  URL
     * @return array{title:string,description:string,image:string}
     */
    private function extract_youtube_channel_metadata_from_json_ld( $html, $url ) {
        $metadata = array(
            'title'       => '',
            'description' => '',
            'image'       => '',
        );

        if ( ! preg_match_all( '#<script[^>]*type=["\']application/ld\+json["\'][^>]*>(.*?)</script>#is', $html, $matches ) ) {
            return $metadata;
        }

        foreach ( $matches[1] as $json_ld_script ) {
            $json_ld_script = trim( (string) $json_ld_script );
            if ( '' === $json_ld_script ) {
                continue;
            }

            $decoded_json = html_entity_decode( $json_ld_script, ENT_QUOTES | ENT_HTML5, 'UTF-8' );
            $json_ld = json_decode( $decoded_json, true );
            if ( ! is_array( $json_ld ) ) {
                continue;
            }

            $nodes = array();
            if ( isset( $json_ld['@graph'] ) && is_array( $json_ld['@graph'] ) ) {
                $nodes = $json_ld['@graph'];
            } elseif ( isset( $json_ld[0] ) ) {
                $nodes = $json_ld;
            } else {
                $nodes[] = $json_ld;
            }

            foreach ( $nodes as $node ) {
                if ( ! is_array( $node ) ) {
                    continue;
                }

                $candidate_url = isset( $node['url'] ) ? (string) $node['url'] : '';
                if ( '' !== $candidate_url ) {
                    $candidate_host = wp_parse_url( $candidate_url, PHP_URL_HOST );
                    if ( is_string( $candidate_host ) && '' !== $candidate_host && ! $this->is_youtube_host( strtolower( $candidate_host ) ) ) {
                        continue;
                    }
                } elseif ( ! $this->is_youtube_channel_url( $url ) ) {
                    continue;
                }

                $title = isset( $node['name'] ) ? trim( (string) $node['name'] ) : '';
                $description = isset( $node['description'] ) ? trim( (string) $node['description'] ) : '';
                $image = $this->extract_json_ld_image( $node );

                if ( '' === $title && '' === $description && '' === $image ) {
                    continue;
                }

                if ( '' === $metadata['title'] && '' !== $title ) {
                    $metadata['title'] = $title;
                }
                if ( '' === $metadata['description'] && '' !== $description ) {
                    $metadata['description'] = $description;
                }
                if ( '' === $metadata['image'] && '' !== $image ) {
                    $metadata['image'] = $image;
                }
            }
        }

        return $metadata;
    }

    /**
     * YouTubeページの channelMetadataRenderer からチャンネルメタ情報を抽出
     *
     * @param string $html HTML
     * @return array{title:string,description:string,image:string}
     */
    private function extract_youtube_channel_metadata_from_initial_data( $html ) {
        $metadata = array(
            'title'       => '',
            'description' => '',
            'image'       => '',
        );

        if ( preg_match( '/"channelMetadataRenderer"\s*:\s*\{.*?"title"\s*:\s*"((?:\\\\.|[^"\\\\])*)"/s', $html, $title_match ) ) {
            $metadata['title'] = $this->decode_json_string_literal( $title_match[1] );
        }

        if ( preg_match( '/"channelMetadataRenderer"\s*:\s*\{.*?"description"\s*:\s*"((?:\\\\.|[^"\\\\])*)"/s', $html, $description_match ) ) {
            $metadata['description'] = $this->decode_json_string_literal( $description_match[1] );
        }

        if ( preg_match( '/"avatar"\s*:\s*\{.*?"url"\s*:\s*"((?:\\\\.|[^"\\\\])*)"/s', $html, $image_match ) ) {
            $metadata['image'] = $this->decode_json_string_literal( $image_match[1] );
        }

        return $metadata;
    }

    /**
     * XPathクエリ群から最初の属性値を抽出
     *
     * @param \DOMXPath $xpath      XPath
     * @param array     $queries    XPathクエリ
     * @param string    $attribute  属性名
     * @return string
     */
    private function extract_first_xpath_attribute( $xpath, $queries, $attribute = 'content' ) {
        foreach ( $queries as $query ) {
            $nodes = $xpath->query( $query );
            if ( ! $nodes instanceof \DOMNodeList || 0 === $nodes->length ) {
                continue;
            }

            $node = $nodes->item( 0 );
            if ( ! $node instanceof \DOMElement ) {
                continue;
            }

            $value = trim( (string) $node->getAttribute( $attribute ) );
            if ( '' !== $value ) {
                return $value;
            }
        }

        return '';
    }

    /**
     * JSON-LDノードから画像URLを抽出
     *
     * @param array $node JSON-LDノード
     * @return string
     */
    private function extract_json_ld_image( $node ) {
        if ( isset( $node['thumbnailUrl'] ) && is_string( $node['thumbnailUrl'] ) ) {
            return trim( $node['thumbnailUrl'] );
        }

        if ( empty( $node['image'] ) ) {
            return '';
        }

        if ( is_string( $node['image'] ) ) {
            return trim( $node['image'] );
        }

        if ( is_array( $node['image'] ) ) {
            if ( isset( $node['image']['url'] ) && is_string( $node['image']['url'] ) ) {
                return trim( $node['image']['url'] );
            }
            if ( isset( $node['image'][0] ) && is_string( $node['image'][0] ) ) {
                return trim( $node['image'][0] );
            }
            if ( isset( $node['image'][0]['url'] ) && is_string( $node['image'][0]['url'] ) ) {
                return trim( $node['image'][0]['url'] );
            }
        }

        return '';
    }

    /**
     * JSON文字列リテラルをデコード
     *
     * @param string $value エスケープ済み文字列
     * @return string
     */
    private function decode_json_string_literal( $value ) {
        if ( ! is_string( $value ) || '' === $value ) {
            return '';
        }

        $decoded = json_decode( '"' . $value . '"' );
        if ( is_string( $decoded ) ) {
            return trim( $decoded );
        }

        return trim( stripcslashes( $value ) );
    }

    /**
     * YouTube URLから動画IDを抽出
     *
     * @param string $url URL
     * @return string 動画ID（11文字）または空文字
     */
    private function extract_youtube_video_id( $url ) {
        $parsed = wp_parse_url( $url );
        if ( ! is_array( $parsed ) || empty( $parsed['host'] ) ) {
            return '';
        }

        $host = strtolower( $parsed['host'] );
        $path = isset( $parsed['path'] ) ? trim( (string) $parsed['path'], '/' ) : '';
        $segments = array_values( array_filter( explode( '/', $path ), 'strlen' ) );

        // youtu.be/{id}
        if ( 'youtu.be' === $host || 'www.youtu.be' === $host ) {
            $candidate = isset( $segments[0] ) ? (string) $segments[0] : '';
            return preg_match( '/^[A-Za-z0-9_-]{11}$/', $candidate ) ? $candidate : '';
        }

        // youtube.com/watch?v={id}
        if ( isset( $parsed['query'] ) ) {
            parse_str( (string) $parsed['query'], $query_args );
            if ( ! empty( $query_args['v'] ) ) {
                $candidate = sanitize_text_field( (string) $query_args['v'] );
                if ( preg_match( '/^[A-Za-z0-9_-]{11}$/', $candidate ) ) {
                    return $candidate;
                }
            }
        }

        // youtube.com/shorts/{id}, /embed/{id}, /live/{id}, /v/{id}
        if ( isset( $segments[0], $segments[1] ) ) {
            if ( in_array( $segments[0], array( 'shorts', 'embed', 'live', 'v' ), true ) ) {
                $candidate = sanitize_text_field( (string) $segments[1] );
                if ( preg_match( '/^[A-Za-z0-9_-]{11}$/', $candidate ) ) {
                    return $candidate;
                }
            }
        }

        return '';
    }

    /**
     * YouTube URLからチャンネル識別子を抽出
     *
     * @param string $url URL
     * @return string チャンネル識別子（@handle など）
     */
    private function extract_youtube_channel_label( $url ) {
        $parsed = wp_parse_url( $url );
        if ( ! is_array( $parsed ) || empty( $parsed['path'] ) ) {
            return '';
        }

        $path = trim( (string) $parsed['path'], '/' );
        if ( '' === $path ) {
            return '';
        }

        $segments = array_values( array_filter( explode( '/', $path ), 'strlen' ) );
        if ( empty( $segments ) ) {
            return '';
        }

        $first_segment = (string) $segments[0];
        if ( 0 === strpos( $first_segment, '@' ) && strlen( $first_segment ) > 1 ) {
            return sanitize_text_field( $first_segment );
        }

        if ( isset( $segments[1] ) && in_array( $first_segment, array( 'channel', 'c', 'user' ), true ) ) {
            return sanitize_text_field( (string) $segments[1] );
        }

        return '';
    }

    /**
     * X（Twitter）の特別処理
     *
     * X/TwitterはJavaScriptでOGPを動的生成するため、通常のHTTPリクエストでは取得できない
     * oEmbed APIを使用して基本情報を取得
     *
     * @param string $url URL
     * @return array|false OGPデータまたはfalse（Xでない場合）
     */
    private function fetch_twitter_data( $url ) {
        // URLをパース
        $parsed = wp_parse_url( $url );
        $host = isset( $parsed['host'] ) ? strtolower( $parsed['host'] ) : '';
        $path = isset( $parsed['path'] ) ? $parsed['path'] : '';
        
        // X/Twitterドメインチェック（シンプルに）
        if ( $host !== 'x.com' && $host !== 'twitter.com' && $host !== 'www.x.com' && $host !== 'www.twitter.com' ) {
            return false;
        }
        
        // パスからユーザー名を抽出（/username 形式）
        $path_parts = explode( '/', trim( $path, '/' ) );
        $username = isset( $path_parts[0] ) ? $path_parts[0] : '';
        
        if ( empty( $username ) ) {
            return false;
        }
        
        // ツイートURLかどうか判定（/username/status/123 形式）
        $is_tweet = ( isset( $path_parts[1] ) && $path_parts[1] === 'status' && isset( $path_parts[2] ) );
        
        // プロフィール情報を返す
        if ( $is_tweet ) {
            return array(
                'title'       => $username . 'の投稿 / X',
                'description' => $username . 'さんの投稿。X（旧Twitter）で詳細を確認しましょう。',
                'image'       => '',
                'url'         => $url,
                'site_name'   => 'X (Twitter)',
                'domain'      => 'x.com',
                'favicon'     => 'https://abs.twimg.com/favicons/twitter.2.ico',
            );
        } else {
            return array(
                'title'       => $username . ' (@' . $username . ') / X',
                'description' => $username . 'さんのプロフィール。X（旧Twitter）で最新の投稿をチェックしましょう。',
                'image'       => '',
                'url'         => $url,
                'site_name'   => 'X (Twitter)',
                'domain'      => 'x.com',
                'favicon'     => 'https://abs.twimg.com/favicons/twitter.2.ico',
            );
        }
    }
}
