<?php
/**
 * OGP Fetcher
 *
 * OGPデータを取得するクラス
 *
 * @package Simple_Link_Card
 */

namespace Simple_Link_Card;

// 万全の防御策
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Class OGP_Fetcher
 */
class OGP_Fetcher {

    /**
     * インスタンス
     *
     * @var OGP_Fetcher|null
     */
    private static $instance = null;

    /**
     * コンストラクタ
     */
    private function __construct() {
    }

    /**
     * インスタンスを取得
     *
     * @return OGP_Fetcher
     */
    public static function get_instance() {
        if ( null === self::$instance ) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * URLからOGPデータを取得
     *
     * @param string $url URL
     * @return array|\WP_ERROR OGPデータまたはエラー
     */
    public function fetch( $url ) {
        // URLのバリデーション
        if ( empty( $url ) ) {
            return new \WP_Error( 'empty_url', __( 'URLが空です。', 'simple-link-card' ) );
        }

        if ( ! filter_var( $url, FILTER_VALIDATE_URL ) ) {
            return new \WP_Error( 'invalid_url', __( '無効なURLです。', 'simple-link-card' ) );
        }

        // SSRF対策：URLスキームとホストの検証
        $parsed = wp_parse_url( $url );
        
        // HTTP/HTTPSのみ許可
        if ( ! isset( $parsed['scheme'] ) || ! in_array( $parsed['scheme'], array( 'http', 'https' ), true ) ) {
            return new \WP_Error( 'invalid_scheme', __( '許可されていないURLスキームです。', 'simple-link-card' ) );
        }
        
        // ホストの検証
        $host = isset( $parsed['host'] ) ? strtolower( $parsed['host'] ) : '';
        if ( empty( $host ) ) {
            return new \WP_Error( 'invalid_host', __( '無効なホストです。', 'simple-link-card' ) );
        }
        
        // ローカルホストと内部アドレスをブロック
        $blocked_hosts = array( 'localhost', '127.0.0.1', '0.0.0.0', '::1', '169.254.169.254' );
        if ( in_array( $host, $blocked_hosts, true ) ) {
            return new \WP_Error( 'blocked_host', __( 'アクセスが制限されているホストです。', 'simple-link-card' ) );
        }
        
        // IPアドレスの場合、プライベート範囲をブロック
        $ip = filter_var( $host, FILTER_VALIDATE_IP );
        if ( $ip !== false ) {
            if ( ! filter_var( $ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE ) ) {
                return new \WP_Error( 'private_ip_blocked', __( 'プライベートIPアドレスへのアクセスは許可されていません。', 'simple-link-card' ) );
            }
        }

        // WordPressの安全なURL検証（DNS解決を含む）
        $validated_url = wp_http_validate_url( $url );
        if ( false === $validated_url ) {
            return new \WP_Error( 'invalid_url', __( '無効なURLです。', 'simple-link-card' ) );
        }

        $url = $validated_url;

        // キャッシュのチェック
        $cache_manager = Cache_Manager::get_instance();
        $cached_data   = $cache_manager->get( $url );

        if ( false !== $cached_data ) {
            if ( ! $this->is_legacy_truncated_cache( $cached_data ) ) {
                return $cached_data;
            }

            // Remove old cached descriptions generated by previous 200-char truncation logic.
            $cache_manager->delete( $url );
        }

        // X（Twitter）の特別処理
        $twitter_data = $this->fetch_twitter_data( $url );
        if ( $twitter_data !== false ) {
            $cache_manager->set( $url, $twitter_data );
            return $twitter_data;
        }

        // HTMLの取得
        $response = wp_safe_remote_get( $url, array(
            'timeout'             => 15,
            'sslverify'           => true,
            'user-agent'          => 'Mozilla/5.0 (compatible; SimpleLinkCard/1.0; +https://monopedia.jp)',
            'limit_response_size' => 500 * KB_IN_BYTES, // 500KB
            'reject_unsafe_urls'  => true,
        ) );

        if ( is_wp_error( $response ) ) {
            return new \WP_Error( 'http_error', $response->get_error_message() );
        }

        $status_code = wp_remote_retrieve_response_code( $response );
        if ( $status_code !== 200 ) {
            /* translators: %d: HTTP status code. */
            return new \WP_Error( 'http_error', sprintf( __( 'HTTPエラー: %d', 'simple-link-card' ), $status_code ) );
        }

        $html = wp_remote_retrieve_body( $response );

        // HTMLの解析
        $ogp_data = $this->parse_html( $html, $url );

        if ( is_wp_error( $ogp_data ) ) {
            return $ogp_data;
        }

        // キャッシュに保存
        $cache_manager->set( $url, $ogp_data );

        /**
         * OGPデータフィルター
         *
         * @param array  $ogp_data 取得したOGPデータ
         * @param string $url      元のURL
         */
        return apply_filters( 'simple_link_card_ogp_data', $ogp_data, $url );
    }

    /**
     * HTMLを解析してOGPデータを抽出
     *
     * @param string $html HTML
     * @param string $url  元のURL
     * @return array|\WP_ERROR OGPデータまたはエラー
     */
    private function parse_html( $html, $url ) {
        // DOMDocumentの準備（現在のlibxml設定を保存）
        $libxml_internal_errors = libxml_use_internal_errors( true );
        $dom = new \DOMDocument();

        // HTMLの読み込み（UTF-8エンコーディングを明示・PHP 8.2互換）
        $html = '<?xml encoding="UTF-8">' . $html;

        // エラー抑制を使用せず、libxmlで内部エラー処理
        $loaded = $dom->loadHTML( $html );
        libxml_clear_errors();

        if ( ! $loaded ) {
            libxml_use_internal_errors( $libxml_internal_errors ); // 設定を元に戻す
            return new \WP_Error( 'parse_error', __( 'HTMLの解析に失敗しました。', 'simple-link-card' ) );
        }

        // XPathの準備
        $xpath = new \DOMXPath( $dom );

        // OGPデータの抽出
        $ogp_data = array(
            'title'       => $this->get_meta_content( $xpath, 'og:title' ),
            'description' => $this->get_meta_content( $xpath, 'og:description' ),
            'image'       => $this->get_meta_content( $xpath, 'og:image' ),
            'url'         => $this->get_meta_content( $xpath, 'og:url' ),
            'site_name'   => $this->get_meta_content( $xpath, 'og:site_name' ),
        );

        // フォールバックデータの取得
        if ( empty( $ogp_data['title'] ) ) {
            $ogp_data['title'] = $this->get_title( $xpath );
        }
        if ( empty( $ogp_data['description'] ) ) {
            $ogp_data['description'] = $this->get_meta_content( $xpath, 'description' );
        }
        if ( empty( $ogp_data['url'] ) ) {
            $ogp_data['url'] = $url;
        }

        // URLを絶対URLに変換
        if ( ! empty( $ogp_data['image'] ) ) {
            $ogp_data['image'] = $this->make_absolute_url( $ogp_data['image'], $url );
        }

        // ドメインの抽出
        $parsed_url = wp_parse_url( $url );
        $ogp_data['domain'] = isset( $parsed_url['host'] ) ? $parsed_url['host'] : '';

        // ファビコンのURL（Googleのサービスを使用）
        if ( ! empty( $ogp_data['domain'] ) ) {
            $ogp_data['favicon'] = 'https://www.google.com/s2/favicons?domain=' . urlencode( $ogp_data['domain'] ) . '&sz=32';
        }

        libxml_use_internal_errors( $libxml_internal_errors ); // 設定を元に戻す
        return $ogp_data;
    }

    /**
     * 旧バージョンで保存された省略キャッシュかどうかを判定
     *
     * @param mixed $cached_data キャッシュデータ
     * @return bool
     */
    private function is_legacy_truncated_cache( $cached_data ) {
        if ( ! is_array( $cached_data ) || empty( $cached_data['description'] ) || ! is_string( $cached_data['description'] ) ) {
            return false;
        }

        $description = trim( $cached_data['description'] );
        if ( '' === $description || '...' !== substr( $description, -3 ) ) {
            return false;
        }

        $length = function_exists( 'mb_strlen' ) ? mb_strlen( $description, 'UTF-8' ) : strlen( $description );
        return 203 === $length;
    }

    /**
     * メタタグのcontentを取得
     *
     * @param \DOMXPath $xpath      XPathオブジェクト
     * @param string    $property   プロパティ名またはname属性
     * @return string 内容
     */
    private function get_meta_content( $xpath, $property ) {
        // property属性で検索（OGP用）
        $query = sprintf( '//meta[@property="%s"]', $property );
        $nodes = $xpath->query( $query );

        if ( $nodes->length > 0 ) {
            return $nodes->item( 0 )->getAttribute( 'content' );
        }

        // name属性で検索（通常のmetaタグ用）
        $query = sprintf( '//meta[@name="%s"]', $property );
        $nodes = $xpath->query( $query );

        if ( $nodes->length > 0 ) {
            return $nodes->item( 0 )->getAttribute( 'content' );
        }

        return '';
    }

    /**
     * ページタイトルを取得
     *
     * @param \DOMXPath $xpath XPathオブジェクト
     * @return string タイトル
     */
    private function get_title( $xpath ) {
        // titleタグ
        $nodes = $xpath->query( '//title' );
        if ( $nodes->length > 0 ) {
            return trim( $nodes->item( 0 )->textContent );
        }

        // h1タグ（フォールバック）
        $nodes = $xpath->query( '//h1' );
        if ( $nodes->length > 0 ) {
            return trim( $nodes->item( 0 )->textContent );
        }

        return '';
    }

    /**
     * 相対URLを絶対URLに変換
     *
     * @param string $url    変換するURL
     * @param string $base   ベースURL
     * @return string 絶対URL
     */
    private function make_absolute_url( $url, $base ) {
        // 既に絶対URLの場合
        if ( preg_match( '#^https?://#i', $url ) ) {
            return $url;
        }

        // プロトコル相対URL
        if ( strpos( $url, '//' ) === 0 ) {
            $parsed = wp_parse_url( $base );
            $scheme = isset( $parsed['scheme'] ) ? $parsed['scheme'] : 'https';
            return $scheme . ':' . $url;
        }

        // 相対パス
        $parsed_base = wp_parse_url( $base );
        $scheme = isset( $parsed_base['scheme'] ) ? $parsed_base['scheme'] : 'https';
        $host = isset( $parsed_base['host'] ) ? $parsed_base['host'] : '';

        if ( strpos( $url, '/' ) === 0 ) {
            return $scheme . '://' . $host . $url;
        }

        // カレントディレクトリからの相対パス
        $path = isset( $parsed_base['path'] ) ? dirname( $parsed_base['path'] ) : '';
        return $scheme . '://' . $host . $path . '/' . $url;
    }

    /**
     * X（Twitter）の特別処理
     *
     * X/TwitterはJavaScriptでOGPを動的生成するため、通常のHTTPリクエストでは取得できない
     * oEmbed APIを使用して基本情報を取得
     *
     * @param string $url URL
     * @return array|false OGPデータまたはfalse（Xでない場合）
     */
    private function fetch_twitter_data( $url ) {
        // URLをパース
        $parsed = wp_parse_url( $url );
        $host = isset( $parsed['host'] ) ? strtolower( $parsed['host'] ) : '';
        $path = isset( $parsed['path'] ) ? $parsed['path'] : '';
        
        // X/Twitterドメインチェック（シンプルに）
        if ( $host !== 'x.com' && $host !== 'twitter.com' && $host !== 'www.x.com' && $host !== 'www.twitter.com' ) {
            return false;
        }
        
        // パスからユーザー名を抽出（/username 形式）
        $path_parts = explode( '/', trim( $path, '/' ) );
        $username = isset( $path_parts[0] ) ? $path_parts[0] : '';
        
        if ( empty( $username ) ) {
            return false;
        }
        
        // ツイートURLかどうか判定（/username/status/123 形式）
        $is_tweet = ( isset( $path_parts[1] ) && $path_parts[1] === 'status' && isset( $path_parts[2] ) );
        
        // プロフィール情報を返す
        if ( $is_tweet ) {
            return array(
                'title'       => $username . 'の投稿 / X',
                'description' => $username . 'さんの投稿。X（旧Twitter）で詳細を確認しましょう。',
                'image'       => '',
                'url'         => $url,
                'site_name'   => 'X (Twitter)',
                'domain'      => 'x.com',
                'favicon'     => 'https://abs.twimg.com/favicons/twitter.2.ico',
            );
        } else {
            return array(
                'title'       => $username . ' (@' . $username . ') / X',
                'description' => $username . 'さんのプロフィール。X（旧Twitter）で最新の投稿をチェックしましょう。',
                'image'       => '',
                'url'         => $url,
                'site_name'   => 'X (Twitter)',
                'domain'      => 'x.com',
                'favicon'     => 'https://abs.twimg.com/favicons/twitter.2.ico',
            );
        }
    }
}
